import type { Database } from "@/lib/database/supabase"

export type CuisineType = Database["public"]["Enums"]["cuisine_type_enum"]
export type MealType = Database["public"]["Enums"]["meal_type_enum"]
export type ProteinType = Database["public"]["Enums"]["protein_type_enum"]
export type DifficultyLevel = Database["public"]["Enums"]["recipe_difficulty"]
export type RecipeTag = Database["public"]["Enums"]["tags_enum"]

export type MockIngredient = {
  name: string
  quantity?: number
  unit?: string
  standardizedIngredientId?: string | null
}

export type MockRecipe = {
  title: string
  cuisine: CuisineType
  mealType: MealType
  protein: ProteinType
  difficulty: DifficultyLevel
  servings: number
  prepTime: number
  cookTime: number
  tags: RecipeTag[]
  nutrition: {
    calories: number
    protein: number
    carbs: number
    fat: number
  }
  description: string
  imageUrl?: string
  instructions: string[]
  ingredients: MockIngredient[]
}

export const RPC_NAME = "fn_upsert_recipe_with_ingredients"

const stripIngredient = (ingredient: MockIngredient) => {
  const displayName = ingredient.name.trim()
  if (!displayName) return null

  return {
    display_name: displayName,
    standardized_ingredient_id: ingredient.standardizedIngredientId ?? null,
    quantity: ingredient.quantity ?? null,
    units: ingredient.unit ?? null,
  }
}

export function buildMockRecipePayload(recipe: MockRecipe, authorId: string) {
  const ingredients = recipe.ingredients
    .map(stripIngredient)
    .filter((item): item is NonNullable<ReturnType<typeof stripIngredient>> => Boolean(item))

  return {
    p_title: recipe.title,
    p_author_id: authorId,
    p_cuisine: recipe.cuisine,
    p_meal_type: recipe.mealType,
    p_protein: recipe.protein,
    p_difficulty: recipe.difficulty,
    p_servings: recipe.servings,
    p_prep_time: recipe.prepTime,
    p_cook_time: recipe.cookTime,
    p_tags: recipe.tags,
    p_nutrition: recipe.nutrition,
    p_description: recipe.description,
    p_image_url: recipe.imageUrl ?? null,
    p_instructions: recipe.instructions,
    p_ingredients: ingredients,
  }
}

export const MOCK_RECIPES: MockRecipe[] = [
  {
    title: "Smoky Chipotle Chicken Tacos",
    cuisine: "mexican",
    mealType: "dinner",
    protein: "chicken",
    difficulty: "intermediate",
    servings: 4,
    prepTime: 15,
    cookTime: 20,
    tags: ["contains-dairy"],
    nutrition: {
      calories: 540,
      protein: 38,
      carbs: 44,
      fat: 22,
    },
    description:
      "Charred chipotle chicken tucked into grilled corn tortillas with lime, cilantro, and pickled onions.",
    imageUrl: "https://images.unsplash.com/photo-1528701800489-20fcfd7f5de5?auto=format&fit=crop&w=800&q=80",
    instructions: [
      "Whisk chipotle peppers, lime juice, olive oil, garlic, and oregano in a bowl, then marinate the chicken for at least 15 minutes.",
      "Sear the chicken on medium-high heat until cooked through, about 4-5 minutes per side, then let it rest before slicing.",
      "Warm tortillas over an open flame or skillet, then assemble tacos with sliced chicken, cilantro, pickled onions, and cotija.",
      "Finish with a squeeze of lime and a drizzle of crema.",
    ],
    ingredients: [
      { name: "boneless skinless chicken thighs", quantity: 1.25, unit: "lb" },
      { name: "chipotle peppers in adobo", quantity: 2, unit: "tbsp" },
      { name: "fresh lime juice", quantity: 2, unit: "tbsp" },
      { name: "extra virgin olive oil", quantity: 2, unit: "tbsp" },
      { name: "garlic cloves", quantity: 3, unit: "clove" },
      { name: "corn tortillas", quantity: 8, unit: "count" },
      { name: "fresh cilantro", quantity: 0.5, unit: "cup" },
      { name: "red onion", quantity: 0.25, unit: "cup" },
      { name: "cotija cheese", quantity: 0.25, unit: "cup" },
    ],
  },
  {
    title: "Mediterranean Chickpea Bowl",
    cuisine: "mediterranean",
    mealType: "lunch",
    protein: "legume",
    difficulty: "beginner",
    servings: 3,
    prepTime: 20,
    cookTime: 10,
    tags: ["vegetarian", "gluten-free"],
    nutrition: {
      calories: 420,
      protein: 18,
      carbs: 52,
      fat: 16,
    },
    description: "A bright bowl packed with chickpeas, quinoa, charred veg, and a lemon-tahini dressing.",
    imageUrl: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=900&q=80",
    instructions: [
      "Cook quinoa according to package directions and fluff with a fork.",
      "Toss cherry tomatoes, zucchini, and bell pepper with olive oil, salt, and pepper; roast until tender and slightly charred.",
      "Whisk tahini, lemon juice, garlic, smoked paprika, and warm water to make a drizzling dressing.",
      "Layer quinoa, roasted vegetables, chickpeas, and spinach in bowls, then finish with dressing and a sprinkle of za'atar.",
    ],
    ingredients: [
      { name: "cooked quinoa", quantity: 1, unit: "cup" },
      { name: "canned chickpeas", quantity: 1.5, unit: "cup" },
      { name: "cherry tomatoes", quantity: 1, unit: "cup" },
      { name: "zucchini", quantity: 1, unit: "each" },
      { name: "red bell pepper", quantity: 1, unit: "each" },
      { name: "baby spinach", quantity: 2, unit: "cup" },
      { name: "extra virgin olive oil", quantity: 3, unit: "tbsp" },
      { name: "lemon juice", quantity: 3, unit: "tbsp" },
      { name: "tahini", quantity: 2, unit: "tbsp" },
      { name: "smoked paprika", quantity: 1, unit: "tsp" },
    ],
  },
  {
    title: "Ginger Miso Salmon",
    cuisine: "japanese",
    mealType: "dinner",
    protein: "fish",
    difficulty: "intermediate",
    servings: 2,
    prepTime: 10,
    cookTime: 15,
    tags: ["contains-soy", "contains-gluten"],
    nutrition: {
      calories: 610,
      protein: 45,
      carbs: 18,
      fat: 32,
    },
    description: "Soy-miso glazed salmon roasted with ginger and sesame for a quick weeknight dinner.",
    imageUrl: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=900&q=80",
    instructions: [
      "Whisk miso paste, soy sauce, honey, rice vinegar, ginger, and sesame oil into a glossy glaze.",
      "Brush the glaze over salmon fillets and let marinate for 10 minutes.",
      "Bake the salmon at 425°F (220°C) for 10-12 minutes until just cooked through, then broil for 1-2 minutes to caramelize.",
      "Garnish with sliced scallions and toasted sesame seeds before serving.",
    ],
    ingredients: [
      { name: "salmon fillets", quantity: 1.25, unit: "lb" },
      { name: "white miso paste", quantity: 2, unit: "tbsp" },
      { name: "low sodium soy sauce", quantity: 3, unit: "tbsp" },
      { name: "honey", quantity: 1.5, unit: "tbsp" },
      { name: "rice vinegar", quantity: 1, unit: "tbsp" },
      { name: "fresh ginger", quantity: 1, unit: "tbsp" },
      { name: "sesame oil", quantity: 1, unit: "tsp" },
      { name: "scallions", quantity: 2, unit: "stalk" },
    ],
  },
  {
    title: "Lemon Tarragon Roasted Cod",
    cuisine: "french",
    mealType: "dinner",
    protein: "fish",
    difficulty: "beginner",
    servings: 4,
    prepTime: 15,
    cookTime: 18,
    tags: ["gluten-free"],
    nutrition: {
      calories: 380,
      protein: 38,
      carbs: 12,
      fat: 18,
    },
    description: "Bright lemon and tarragon-roasted cod served with blistered veggies for an easy weeknight dinner.",
    imageUrl: "https://images.unsplash.com/photo-1512058564366-c9e3c5b8051b?auto=format&fit=crop&w=900&q=80",
    instructions: [
      "Preheat oven to 425°F (220°C) and line a sheet pan with parchment.",
      "Place cod fillets on the pan, drizzle with olive oil, lemon zest, minced garlic, chopped tarragon, salt, and pepper.",
      "Roast for 12-14 minutes until the fish flakes easily, adding thinly sliced lemons and asparagus to the pan halfway through.",
      "Serve with extra lemon wedges and a scattering of fresh tarragon leaves.",
    ],
    ingredients: [
      { name: "cod fillets", quantity: 1.5, unit: "lb" },
      { name: "extra virgin olive oil", quantity: 2, unit: "tbsp" },
      { name: "fresh lemon zest", quantity: 1, unit: "tbsp" },
      { name: "fresh lemon juice", quantity: 2, unit: "tbsp" },
      { name: "garlic cloves", quantity: 3, unit: "clove" },
      { name: "fresh tarragon", quantity: 0.25, unit: "cup" },
      { name: "asparagus spears", quantity: 1, unit: "bunch" },
      { name: "lemon", quantity: 1, unit: "each" },
    ],
  },
  {
    title: "Thai Basil Beef Noodles",
    cuisine: "thai",
    mealType: "dinner",
    protein: "beef",
    difficulty: "intermediate",
    servings: 4,
    prepTime: 20,
    cookTime: 15,
    tags: ["contains-soy"],
    nutrition: {
      calories: 610,
      protein: 36,
      carbs: 62,
      fat: 24,
    },
    description: "Sizzling beef tossed with rice noodles, basil, and fiery chili garlicky sauce for a takeout-style dinner.",
    imageUrl: "https://images.unsplash.com/photo-1543353071-873f17a7a088?auto=format&fit=crop&w=900&q=80",
    instructions: [
      "Soak rice noodles in hot water until pliable, then drain and set aside.",
      "Stir-fry thinly sliced beef with fish sauce, tamari, brown sugar, garlic, and Thai chilies until browned.",
      "Add shallots, bell pepper, and the noodles, tossing with oyster sauce and a splash of rice vinegar until coated.",
      "Finish with a generous handful of Thai basil leaves and serve with lime wedges.",
    ],
    ingredients: [
      { name: "rice noodles", quantity: 8, unit: "oz" },
      { name: "flank steak", quantity: 1, unit: "lb" },
      { name: "garlic cloves", quantity: 4, unit: "clove" },
      { name: "Thai bird chilies", quantity: 2, unit: "each" },
      { name: "fish sauce", quantity: 1.5, unit: "tbsp" },
      { name: "low sodium tamari", quantity: 1.5, unit: "tbsp" },
      { name: "oyster sauce", quantity: 2, unit: "tbsp" },
      { name: "Thai basil leaves", quantity: 1, unit: "cup" },
      { name: "bell pepper", quantity: 1, unit: "each" },
      { name: "lime", quantity: 1, unit: "each" },
    ],
  },
  {
    title: "Middle Eastern Chickpea & Eggplant Stew",
    cuisine: "middle-eastern",
    mealType: "lunch",
    protein: "legume",
    difficulty: "intermediate",
    servings: 4,
    prepTime: 25,
    cookTime: 35,
    tags: ["vegetarian", "gluten-free"],
    nutrition: {
      calories: 460,
      protein: 18,
      carbs: 60,
      fat: 18,
    },
    description: "A warming stew of roasted eggplant, chickpeas, and fragrant Middle Eastern spices.",
    imageUrl: "https://images.unsplash.com/photo-1512058564366-c9e3c5b8051b?auto=format&fit=crop&w=800&q=80",
    instructions: [
      "Roast diced eggplant tossed with olive oil until the cubes are golden and tender.",
      "Sauté onion, garlic, and shaved carrots with cumin, coriander, smoked paprika, and a pinch of cinnamon.",
      "Add chickpeas, roasted eggplant, tomatoes, and vegetable broth, then simmer for 20 minutes to develop flavor.",
      "Finish with fresh parsley, lemon juice, and serve over fluffy couscous or rice.",
    ],
    ingredients: [
      { name: "eggplant", quantity: 2, unit: "each" },
      { name: "canned chickpeas", quantity: 2, unit: "cup" },
      { name: "onion", quantity: 1, unit: "each" },
      { name: "garlic cloves", quantity: 4, unit: "clove" },
      { name: "tomatoes", quantity: 2, unit: "cup" },
      { name: "vegetable broth", quantity: 1.5, unit: "cup" },
      { name: "ground cumin", quantity: 1, unit: "tsp" },
      { name: "smoked paprika", quantity: 1, unit: "tsp" },
      { name: "fresh parsley", quantity: 0.25, unit: "cup" },
      { name: "lemon", quantity: 1, unit: "each" },
    ],
  },
  {
    title: "Grilled Corn, Avocado & Black Bean Salad",
    cuisine: "american",
    mealType: "lunch",
    protein: "legume",
    difficulty: "beginner",
    servings: 4,
    prepTime: 15,
    cookTime: 10,
    tags: ["vegetarian", "gluten-free"],
    nutrition: {
      calories: 340,
      protein: 12,
      carbs: 32,
      fat: 18,
    },
    description: "Charred corn, creamy avocado, and black beans tossed with lime and chile for a vibrant salad.",
    imageUrl: "https://images.unsplash.com/photo-1504754524776-8f4f37790ca0?auto=format&fit=crop&w=900&q=80",
    instructions: [
      "Grill corn until lightly charred, then slice kernels into a bowl.",
      "Toss corn with black beans, diced avocado, cherry tomatoes, red onion, and chopped cilantro.",
      "Whisk lime juice, olive oil, honey, and chili flakes, then pour over the salad and gently combine.",
      "Serve chilled or at room temperature with extra cilantro and lime wedges.",
    ],
    ingredients: [
      { name: "fresh corn", quantity: 4, unit: "ear" },
      { name: "canned black beans", quantity: 1.5, unit: "cup" },
      { name: "ripe avocados", quantity: 2, unit: "each" },
      { name: "cherry tomatoes", quantity: 1, unit: "cup" },
      { name: "red onion", quantity: 0.5, unit: "cup" },
      { name: "cilantro", quantity: 0.25, unit: "cup" },
      { name: "lime juice", quantity: 3, unit: "tbsp" },
      { name: "extra virgin olive oil", quantity: 2, unit: "tbsp" },
      { name: "honey", quantity: 1, unit: "tsp" },
    ],
  },
  {
    title: "Coconut Turmeric Lentil Dal",
    cuisine: "indian",
    mealType: "dinner",
    protein: "legume",
    difficulty: "intermediate",
    servings: 4,
    prepTime: 20,
    cookTime: 25,
    tags: ["vegan", "gluten-free"],
    nutrition: {
      calories: 500,
      protein: 22,
      carbs: 58,
      fat: 20,
    },
    description: "Creamy coconut turmeric dal simmered with ginger, garlic, and mustard seeds for a comforting bowl.",
    imageUrl: "https://images.unsplash.com/photo-1500917293891-ef795e70e1f6?auto=format&fit=crop&w=900&q=80",
    instructions: [
      "Rinse red lentils until water runs clear, then simmer with water, turmeric, cinnamon stick, and bay leaf until tender.",
      "Temper mustard seeds, cumin, curry leaves, and dried chilies in ghee, then add onions, garlic, and ginger until golden.",
      "Stir the toasted aromatics into the lentils along with coconut milk, lime juice, and chopped tomatoes; simmer to thicken.",
      "Finish with chopped cilantro, serve with basmati rice, and garnish with toasted coconut or pepitas.",
    ],
    ingredients: [
      { name: "red lentils", quantity: 1.5, unit: "cup" },
      { name: "coconut milk", quantity: 1, unit: "cup" },
      { name: "vegetable broth", quantity: 2, unit: "cup" },
      { name: "onion", quantity: 1, unit: "each" },
      { name: "garlic cloves", quantity: 4, unit: "clove" },
      { name: "fresh ginger", quantity: 1, unit: "tbsp" },
      { name: "mustard seeds", quantity: 1, unit: "tsp" },
      { name: "curry leaves", quantity: 8, unit: "leaf" },
      { name: "cumin seeds", quantity: 1, unit: "tsp" },
      { name: "lime", quantity: 1, unit: "each" },
    ],
  },
  {
    title: "Spicy Korean Pork Bibimbap",
    cuisine: "korean",
    mealType: "dinner",
    protein: "pork",
    difficulty: "intermediate",
    servings: 4,
    prepTime: 20,
    cookTime: 15,
    tags: ["contains-soy"],
    nutrition: {
      calories: 640,
      protein: 33,
      carbs: 68,
      fat: 28,
    },
    description:
      "Caramelized gochujang pork nestled atop warm rice with blistered veggies, a fried egg, and sesame crunch.",
    imageUrl: "https://images.unsplash.com/photo-1525755662778-989d0524087e?auto=format&fit=crop&w=900&q=80",
    instructions: [
      "Sauté ground pork with garlic, ginger, gochujang, soy sauce, sesame oil, and brown sugar until browned and sticky.",
      "Roast broccoli florets and carrots tossed in oil and a pinch of salt until charred at the edges.",
      "Warm rice, then divide among bowls with pork, veggies, and a fried egg per bowl.",
      "Top with cucumber ribbons, kimchi, sesame seeds, and a drizzle of extra sesame oil before serving.",
    ],
    ingredients: [
      { name: "ground pork", quantity: 1.25, unit: "lb" },
      { name: "gochujang", quantity: 2, unit: "tbsp" },
      { name: "soy sauce", quantity: 2, unit: "tbsp" },
      { name: "sesame oil", quantity: 1.5, unit: "tbsp" },
      { name: "brown sugar", quantity: 2, unit: "tbsp" },
      { name: "garlic cloves", quantity: 3, unit: "clove" },
      { name: "fresh ginger", quantity: 1, unit: "tbsp" },
      { name: "broccoli florets", quantity: 2, unit: "cup" },
      { name: "carrots", quantity: 2, unit: "each" },
      { name: "cooked jasmine rice", quantity: 4, unit: "cup" },
      { name: "large eggs", quantity: 4, unit: "each" },
    ],
  },
  {
    title: "Heirloom Tomato & Burrata Toast",
    cuisine: "italian",
    mealType: "lunch",
    protein: "other",
    difficulty: "beginner",
    servings: 2,
    prepTime: 10,
    cookTime: 8,
    tags: ["vegetarian"],
    nutrition: {
      calories: 410,
      protein: 12,
      carbs: 28,
      fat: 26,
    },
    description: "Crunchy sourdough piled with creamy burrata, cornichon tomatoes, and basil oil for a sunny snack.",
    imageUrl: "https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?auto=format&fit=crop&w=900&q=80",
    instructions: [
      "Toast sourdough slices until golden and brush with garlic-infused olive oil.",
      "Halve heirloom tomatoes, drizzle with fine sea salt, and let them macerate while burrata softens.",
      "Top each slice with torn burrata, tomatoes, a scattering of basil leaves, and a pinch of Aleppo pepper.",
      "Finish with a drizzle of extra virgin olive oil and flaky salt right before serving.",
    ],
    ingredients: [
      { name: "sourdough bread", quantity: 4, unit: "slice" },
      { name: "burrata cheese", quantity: 1, unit: "ball" },
      { name: "heirloom tomatoes", quantity: 2, unit: "cup" },
      { name: "fresh basil", quantity: 0.25, unit: "cup" },
      { name: "extra virgin olive oil", quantity: 2, unit: "tbsp" },
      { name: "garlic clove", quantity: 1, unit: "clove" },
      { name: "Aleppo pepper", quantity: 0.5, unit: "tsp" },
    ],
  },
  {
    title: "Moroccan Harissa Carrot & Chickpea Salad",
    cuisine: "middle-eastern",
    mealType: "lunch",
    protein: "legume",
    difficulty: "intermediate",
    servings: 4,
    prepTime: 20,
    cookTime: 15,
    tags: ["vegan", "gluten-free", "dairy-free"],
    nutrition: {
      calories: 340,
      protein: 14,
      carbs: 38,
      fat: 15,
    },
    description: "Roasted carrots and chickpeas tossed with harissa, preserved lemon, and fresh mint for layered heat.",
    imageUrl: "https://images.unsplash.com/photo-1482049016688-2d3e1b311543?auto=format&fit=crop&w=900&q=80",
    instructions: [
      "Roast carrot ribbons and chickpeas coated in harissa paste, olive oil, and maple syrup until caramelized.",
      "Toast cumin and coriander seeds in a dry skillet, then grind with sea salt and preserved lemon rind.",
      "Toss warm veggies with picked mint, chopped parsley, and a squeeze of lemon juice.",
      "Serve over a bed of arugula with toasted almonds and a drizzle of extra olive oil.",
    ],
    ingredients: [
      { name: "carrots", quantity: 4, unit: "each" },
      { name: "canned chickpeas", quantity: 1.5, unit: "cup" },
      { name: "harissa paste", quantity: 2, unit: "tbsp" },
      { name: "maple syrup", quantity: 1, unit: "tbsp" },
      { name: "preserved lemon", quantity: 1, unit: "each" },
      { name: "fresh mint", quantity: 0.25, unit: "cup" },
      { name: "parsley", quantity: 0.25, unit: "cup" },
      { name: "toasted almonds", quantity: 0.25, unit: "cup" },
      { name: "arugula", quantity: 4, unit: "cup" },
    ],
  },
  {
    title: "Thai Coconut Pumpkin Soup",
    cuisine: "thai",
    mealType: "dinner",
    protein: "other",
    difficulty: "intermediate",
    servings: 4,
    prepTime: 15,
    cookTime: 30,
    tags: ["vegetarian", "gluten-free"],
    nutrition: {
      calories: 320,
      protein: 8,
      carbs: 28,
      fat: 20,
    },
    description: "Silky pumpkin puree enriched with coconut milk, lemongrass, and lime for a fragrant bowl.",
    imageUrl: "https://images.unsplash.com/photo-1543353071-873f17a7a088?auto=format&fit=crop&w=900&q=80",
    instructions: [
      "Sweat onions, garlic, and ginger in coconut oil until translucent, then add pumpkin puree and red curry paste.",
      "Pour in vegetable broth and simmer with lemongrass and kaffir lime leaves to let the flavors bloom.",
      "Stir in coconut milk, fish sauce, and lime juice, then blend until smooth if desired.",
      "Serve garnished with cilantro, crushed peanuts, and a drizzle of chili oil.",
    ],
    ingredients: [
      { name: "butternut squash puree", quantity: 2, unit: "cup" },
      { name: "coconut milk", quantity: 1, unit: "cup" },
      { name: "vegetable broth", quantity: 3, unit: "cup" },
      { name: "red curry paste", quantity: 1, unit: "tbsp" },
      { name: "lemongrass stalks", quantity: 2, unit: "each" },
      { name: "kaffir lime leaves", quantity: 4, unit: "leaf" },
      { name: "lime juice", quantity: 2, unit: "tbsp" },
      { name: "cilantro", quantity: 0.25, unit: "cup" },
      { name: "crushed peanuts", quantity: 0.25, unit: "cup" },
      { name: "chili oil", quantity: 1, unit: "tbsp" },
    ],
  },
  {
    title: "Greek Lemon Herb Chicken with Farro",
    cuisine: "greek",
    mealType: "dinner",
    protein: "chicken",
    difficulty: "intermediate",
    servings: 4,
    prepTime: 20,
    cookTime: 35,
    tags: ["gluten-free"],
    nutrition: {
      calories: 580,
      protein: 40,
      carbs: 48,
      fat: 24,
    },
    description: "Marinated chicken thighs roasted with lemon, oregano, and tomatoes, served over herbed farro.",
    imageUrl: "https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?auto=format&fit=crop&w=900&q=80",
    instructions: [
      "Marinate chicken thighs in olive oil, lemon juice, garlic, oregano, and smoked paprika for 30 minutes.",
      "Roast with halved cherry tomatoes and red onion until the chicken reaches 165°F and the veggies caramelize.",
      "Cook farro until tender, then toss with chopped dill, parsley, and lemon zest.",
      "Plate chicken over farro and spoon pan juices with roasted tomatoes on top.",
    ],
    ingredients: [
      { name: "bone-in chicken thighs", quantity: 2, unit: "lb" },
      { name: "olive oil", quantity: 3, unit: "tbsp" },
      { name: "lemon juice", quantity: 3, unit: "tbsp" },
      { name: "garlic cloves", quantity: 4, unit: "clove" },
      { name: "dried oregano", quantity: 2, unit: "tsp" },
      { name: "smoked paprika", quantity: 1, unit: "tsp" },
      { name: "cherry tomatoes", quantity: 1.5, unit: "cup" },
      { name: "red onion", quantity: 1, unit: "each" },
      { name: "farro", quantity: 1, unit: "cup" },
      { name: "fresh dill", quantity: 0.25, unit: "cup" },
      { name: "fresh parsley", quantity: 0.25, unit: "cup" },
    ],
  },
  {
    title: "Vietnamese Lemongrass Shrimp Vermicelli Bowl",
    cuisine: "vietnamese",
    mealType: "dinner",
    protein: "shellfish",
    difficulty: "intermediate",
    servings: 4,
    prepTime: 25,
    cookTime: 12,
    tags: ["contains-shellfish", "dairy-free"],
    nutrition: {
      calories: 470,
      protein: 31,
      carbs: 52,
      fat: 14,
    },
    description: "Warm lemongrass shrimp over chilled vermicelli with herbs, pickled vegetables, and nuoc cham.",
    imageUrl: "https://images.unsplash.com/photo-1555126634-323283e090fa?auto=format&fit=crop&w=900&q=80",
    instructions: [
      "Marinate shrimp with minced lemongrass, fish sauce, garlic, sugar, and black pepper for 15 minutes.",
      "Quick-pickle carrots and daikon in rice vinegar, sugar, and salt while the noodles soak.",
      "Sear shrimp in a hot pan until just opaque and lightly caramelized at the edges.",
      "Layer vermicelli, lettuce, herbs, cucumber, pickles, and shrimp, then spoon over nuoc cham before serving.",
    ],
    ingredients: [
      { name: "large shrimp", quantity: 1.25, unit: "lb" },
      { name: "rice vermicelli noodles", quantity: 8, unit: "oz" },
      { name: "lemongrass stalk", quantity: 2, unit: "each" },
      { name: "fish sauce", quantity: 3, unit: "tbsp" },
      { name: "garlic cloves", quantity: 3, unit: "clove" },
      { name: "rice vinegar", quantity: 0.5, unit: "cup" },
      { name: "carrots", quantity: 2, unit: "each" },
      { name: "daikon radish", quantity: 0.5, unit: "each" },
      { name: "fresh mint", quantity: 0.5, unit: "cup" },
      { name: "fresh Thai basil", quantity: 0.5, unit: "cup" },
      { name: "romaine lettuce", quantity: 3, unit: "cup" },
    ],
  },
  {
    title: "Spanish Chorizo & White Bean Stew",
    cuisine: "spanish",
    mealType: "dinner",
    protein: "pork",
    difficulty: "beginner",
    servings: 4,
    prepTime: 15,
    cookTime: 40,
    tags: ["dairy-free", "gluten-free"],
    nutrition: {
      calories: 560,
      protein: 28,
      carbs: 34,
      fat: 32,
    },
    description: "Smoky chorizo simmers with butter beans, tomato, and saffron for a rich one-pot supper.",
    imageUrl: "https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=900&q=80",
    instructions: [
      "Brown sliced chorizo in a Dutch oven to render fat, then remove and reserve.",
      "Cook onion, fennel, and garlic in the same pot until soft, then stir in smoked paprika and tomato paste.",
      "Add crushed tomatoes, white beans, stock, saffron, and bay leaf; simmer until thickened.",
      "Return chorizo to the pot, fold in spinach, and finish with sherry vinegar and parsley.",
    ],
    ingredients: [
      { name: "Spanish chorizo", quantity: 12, unit: "oz" },
      { name: "canned butter beans", quantity: 3, unit: "cup" },
      { name: "yellow onion", quantity: 1, unit: "each" },
      { name: "fennel bulb", quantity: 1, unit: "each" },
      { name: "garlic cloves", quantity: 4, unit: "clove" },
      { name: "crushed tomatoes", quantity: 2, unit: "cup" },
      { name: "chicken stock", quantity: 1.5, unit: "cup" },
      { name: "smoked paprika", quantity: 2, unit: "tsp" },
      { name: "saffron threads", quantity: 0.25, unit: "tsp" },
      { name: "baby spinach", quantity: 2, unit: "cup" },
      { name: "sherry vinegar", quantity: 1, unit: "tbsp" },
    ],
  },
  {
    title: "Crispy Tofu Rainbow Grain Bowl",
    cuisine: "other",
    mealType: "lunch",
    protein: "tofu",
    difficulty: "intermediate",
    servings: 4,
    prepTime: 25,
    cookTime: 22,
    tags: ["vegan", "contains-soy"],
    nutrition: {
      calories: 510,
      protein: 24,
      carbs: 56,
      fat: 22,
    },
    description: "Crispy tofu, farro, and crunchy produce tossed with ginger-miso tahini dressing.",
    imageUrl: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=900&q=80",
    instructions: [
      "Press tofu, cube it, then toss with cornstarch, tamari, and sesame oil before roasting until crisp.",
      "Cook farro until chewy-tender and cool slightly.",
      "Whisk white miso, tahini, grated ginger, rice vinegar, maple syrup, and warm water into a creamy dressing.",
      "Assemble bowls with farro, tofu, edamame, cabbage, mango, radish, and cucumber, then drizzle with dressing.",
    ],
    ingredients: [
      { name: "extra-firm tofu", quantity: 14, unit: "oz" },
      { name: "cooked farro", quantity: 3, unit: "cup" },
      { name: "shelled edamame", quantity: 1.5, unit: "cup" },
      { name: "red cabbage", quantity: 2, unit: "cup" },
      { name: "mango", quantity: 1, unit: "each" },
      { name: "watermelon radish", quantity: 1, unit: "each" },
      { name: "Persian cucumber", quantity: 2, unit: "each" },
      { name: "white miso paste", quantity: 1, unit: "tbsp" },
      { name: "tahini", quantity: 2, unit: "tbsp" },
      { name: "tamari", quantity: 2, unit: "tbsp" },
      { name: "cornstarch", quantity: 2, unit: "tbsp" },
    ],
  },
  {
    title: "Turkish Menemen with Feta",
    cuisine: "middle-eastern",
    mealType: "breakfast",
    protein: "egg",
    difficulty: "beginner",
    servings: 3,
    prepTime: 10,
    cookTime: 15,
    tags: ["vegetarian", "contains-egg", "contains-dairy", "gluten-free"],
    nutrition: {
      calories: 360,
      protein: 19,
      carbs: 14,
      fat: 24,
    },
    description: "Soft-scrambled eggs with peppers, tomato, and Aleppo pepper, finished with crumbled feta.",
    imageUrl: "https://images.unsplash.com/photo-1484723091739-30a097e8f929?auto=format&fit=crop&w=900&q=80",
    instructions: [
      "Sauté onion and green pepper in olive oil until softened, then add grated tomato and red pepper paste.",
      "Season with Aleppo pepper and simmer until the sauce thickens slightly.",
      "Pour in beaten eggs and gently stir over low heat until softly set.",
      "Top with feta, chopped parsley, and extra olive oil; serve immediately.",
    ],
    ingredients: [
      { name: "large eggs", quantity: 6, unit: "each" },
      { name: "green bell pepper", quantity: 1, unit: "each" },
      { name: "yellow onion", quantity: 0.5, unit: "each" },
      { name: "ripe tomatoes", quantity: 3, unit: "each" },
      { name: "red pepper paste", quantity: 1, unit: "tbsp" },
      { name: "Aleppo pepper", quantity: 1, unit: "tsp" },
      { name: "feta cheese", quantity: 0.5, unit: "cup" },
      { name: "fresh parsley", quantity: 0.25, unit: "cup" },
      { name: "olive oil", quantity: 2, unit: "tbsp" },
    ],
  },
  {
    title: "Dark Chocolate Avocado Mousse Parfaits",
    cuisine: "american",
    mealType: "dessert",
    protein: "other",
    difficulty: "beginner",
    servings: 4,
    prepTime: 15,
    cookTime: 0,
    tags: ["vegan", "gluten-free", "dairy-free", "contains-nuts"],
    nutrition: {
      calories: 330,
      protein: 6,
      carbs: 29,
      fat: 22,
    },
    description: "Silky avocado-cocoa mousse layered with berries, toasted coconut, and pistachio crunch.",
    imageUrl: "https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=900&q=80",
    instructions: [
      "Blend avocado, cocoa powder, maple syrup, vanilla, espresso powder, and coconut milk until completely smooth.",
      "Chill the mousse for 20 minutes to firm up and deepen the chocolate flavor.",
      "Layer mousse with raspberries in small glasses.",
      "Top with toasted coconut flakes, chopped pistachios, and a pinch of flaky salt before serving.",
    ],
    ingredients: [
      { name: "ripe avocados", quantity: 2, unit: "each" },
      { name: "unsweetened cocoa powder", quantity: 0.5, unit: "cup" },
      { name: "coconut milk", quantity: 0.5, unit: "cup" },
      { name: "maple syrup", quantity: 0.25, unit: "cup" },
      { name: "vanilla extract", quantity: 1, unit: "tsp" },
      { name: "espresso powder", quantity: 0.5, unit: "tsp" },
      { name: "fresh raspberries", quantity: 1.5, unit: "cup" },
      { name: "toasted coconut flakes", quantity: 0.25, unit: "cup" },
      { name: "pistachios", quantity: 0.25, unit: "cup" },
    ],
  },
  {
    title: "Classic Southern Fried Chicken & Waffles",
    cuisine: "american",
    mealType: "dinner",
    protein: "chicken",
    difficulty: "advanced",
    servings: 4,
    prepTime: 30,
    cookTime: 35,
    tags: ["contains-gluten", "contains-dairy", "contains-egg"],
    nutrition: {
      calories: 860,
      protein: 42,
      carbs: 72,
      fat: 45,
    },
    description: "Crispy buttermilk fried chicken served over crisp waffles with hot honey and scallions.",
    imageUrl: "https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=900&q=80",
    instructions: [
      "Marinate chicken in buttermilk, hot sauce, garlic powder, and paprika for at least 2 hours.",
      "Whisk waffle batter with flour, eggs, milk, and melted butter, then cook until golden and crisp.",
      "Dredge chicken in seasoned flour and fry at 350°F until deeply golden and cooked through.",
      "Serve chicken over waffles with hot honey, pickles, and chopped scallions.",
    ],
    ingredients: [
      { name: "bone-in chicken pieces", quantity: 2, unit: "lb" },
      { name: "buttermilk", quantity: 2, unit: "cup" },
      { name: "all-purpose flour", quantity: 2.5, unit: "cup" },
      { name: "large eggs", quantity: 3, unit: "each" },
      { name: "whole milk", quantity: 1.25, unit: "cup" },
      { name: "unsalted butter", quantity: 4, unit: "tbsp" },
      { name: "baking powder", quantity: 2, unit: "tsp" },
      { name: "cayenne pepper", quantity: 1, unit: "tsp" },
      { name: "hot sauce", quantity: 2, unit: "tbsp" },
      { name: "honey", quantity: 0.25, unit: "cup" },
      { name: "dill pickles", quantity: 0.5, unit: "cup" },
    ],
  },
  {
    title: "Kansas City BBQ Baby Back Ribs",
    cuisine: "american",
    mealType: "dinner",
    protein: "pork",
    difficulty: "advanced",
    servings: 6,
    prepTime: 25,
    cookTime: 180,
    tags: ["dairy-free", "gluten-free"],
    nutrition: {
      calories: 720,
      protein: 46,
      carbs: 24,
      fat: 48,
    },
    description: "Slow-roasted ribs lacquered with smoky-sweet barbecue sauce and finished on high heat.",
    imageUrl: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=900&q=80",
    instructions: [
      "Rub ribs with brown sugar, paprika, black pepper, mustard powder, and garlic powder.",
      "Wrap and roast low and slow until tender, then unwrap and brush generously with BBQ sauce.",
      "Broil or grill briefly to caramelize the glaze and build charred edges.",
      "Rest, slice between bones, and serve with extra sauce and vinegar slaw.",
    ],
    ingredients: [
      { name: "baby back pork ribs", quantity: 3.5, unit: "lb" },
      { name: "brown sugar", quantity: 0.25, unit: "cup" },
      { name: "smoked paprika", quantity: 2, unit: "tbsp" },
      { name: "garlic powder", quantity: 1, unit: "tbsp" },
      { name: "mustard powder", quantity: 1, unit: "tbsp" },
      { name: "black pepper", quantity: 2, unit: "tsp" },
      { name: "kosher salt", quantity: 2, unit: "tsp" },
      { name: "apple cider vinegar", quantity: 2, unit: "tbsp" },
      { name: "ketchup", quantity: 1, unit: "cup" },
      { name: "molasses", quantity: 2, unit: "tbsp" },
      { name: "Worcestershire sauce", quantity: 1, unit: "tbsp" },
    ],
  },
  {
    title: "New England Clam Chowder",
    cuisine: "american",
    mealType: "lunch",
    protein: "shellfish",
    difficulty: "intermediate",
    servings: 4,
    prepTime: 20,
    cookTime: 35,
    tags: ["contains-shellfish", "contains-dairy"],
    nutrition: {
      calories: 540,
      protein: 24,
      carbs: 34,
      fat: 34,
    },
    description: "Creamy clam chowder with bacon, potatoes, celery, and thyme, finished with oyster crackers.",
    imageUrl: "https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=900&q=80",
    instructions: [
      "Render chopped bacon until crisp, then sauté onion and celery in the drippings.",
      "Add potatoes, clam juice, thyme, and bay leaf; simmer until the potatoes are tender.",
      "Stir in chopped clams, cream, and a flour-butter slurry, then cook gently until thickened.",
      "Season with black pepper and lemon, then serve with parsley and oyster crackers.",
    ],
    ingredients: [
      { name: "canned chopped clams", quantity: 20, unit: "oz" },
      { name: "clam juice", quantity: 2, unit: "cup" },
      { name: "thick-cut bacon", quantity: 6, unit: "slice" },
      { name: "russet potatoes", quantity: 3, unit: "each" },
      { name: "yellow onion", quantity: 1, unit: "each" },
      { name: "celery stalks", quantity: 3, unit: "stalk" },
      { name: "heavy cream", quantity: 1.5, unit: "cup" },
      { name: "unsalted butter", quantity: 2, unit: "tbsp" },
      { name: "all-purpose flour", quantity: 2, unit: "tbsp" },
      { name: "fresh thyme", quantity: 1, unit: "tbsp" },
      { name: "oyster crackers", quantity: 1, unit: "cup" },
    ],
  },
  {
    title: "Berkeley Cheese Board-Style Sourdough Pizza",
    cuisine: "american",
    mealType: "dinner",
    protein: "other",
    difficulty: "advanced",
    servings: 4,
    prepTime: 40,
    cookTime: 18,
    tags: ["vegetarian", "contains-dairy", "contains-gluten"],
    nutrition: {
      calories: 620,
      protein: 22,
      carbs: 74,
      fat: 24,
    },
    description: "Thick sourdough slab pizza topped with creme fraiche, potato, mozzarella, and chili flakes.",
    imageUrl: "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=900&q=80",
    instructions: [
      "Stretch sourdough dough onto an oiled sheet pan and let it proof until airy.",
      "Spread with creme fraiche and garlic, then layer thin potato slices, mozzarella, and scallions.",
      "Bake at high heat until the crust is deeply golden and the cheese bubbles.",
      "Finish with chili flakes, lemon zest, and fresh herbs before slicing.",
    ],
    ingredients: [
      { name: "active sourdough pizza dough", quantity: 1.5, unit: "lb" },
      { name: "creme fraiche", quantity: 0.75, unit: "cup" },
      { name: "low-moisture mozzarella", quantity: 2, unit: "cup" },
      { name: "Yukon gold potato", quantity: 1, unit: "each" },
      { name: "garlic cloves", quantity: 2, unit: "clove" },
      { name: "scallions", quantity: 3, unit: "stalk" },
      { name: "olive oil", quantity: 2, unit: "tbsp" },
      { name: "lemon zest", quantity: 1, unit: "tsp" },
      { name: "red chili flakes", quantity: 1, unit: "tsp" },
      { name: "fresh parsley", quantity: 0.25, unit: "cup" },
    ],
  },
  {
    title: "Berkeley Cafe Tofu Banh Mi",
    cuisine: "vietnamese",
    mealType: "lunch",
    protein: "tofu",
    difficulty: "intermediate",
    servings: 4,
    prepTime: 25,
    cookTime: 15,
    tags: ["vegan", "contains-soy", "contains-gluten"],
    nutrition: {
      calories: 490,
      protein: 21,
      carbs: 58,
      fat: 18,
    },
    description: "Crispy soy-glazed tofu layered in baguette with pickled carrots, jalapeno, and cilantro.",
    imageUrl: "https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=900&q=80",
    instructions: [
      "Press and pan-sear tofu until crisp, then glaze with tamari, maple syrup, and five-spice.",
      "Quick-pickle julienned carrot and daikon in rice vinegar, sugar, and salt.",
      "Toast baguette pieces and spread with vegan mayo and a little chili crisp.",
      "Fill each roll with tofu, pickles, cucumber, jalapeno, and cilantro.",
    ],
    ingredients: [
      { name: "extra-firm tofu", quantity: 14, unit: "oz" },
      { name: "mini baguettes", quantity: 4, unit: "each" },
      { name: "tamari", quantity: 2, unit: "tbsp" },
      { name: "maple syrup", quantity: 1, unit: "tbsp" },
      { name: "Chinese five-spice powder", quantity: 0.5, unit: "tsp" },
      { name: "rice vinegar", quantity: 0.5, unit: "cup" },
      { name: "carrots", quantity: 2, unit: "each" },
      { name: "daikon radish", quantity: 0.5, unit: "each" },
      { name: "Persian cucumber", quantity: 2, unit: "each" },
      { name: "jalapeno", quantity: 1, unit: "each" },
      { name: "fresh cilantro", quantity: 0.5, unit: "cup" },
    ],
  },
  {
    title: "Chez Panisse-Inspired Roast Chicken with Bread Salad",
    cuisine: "american",
    mealType: "dinner",
    protein: "chicken",
    difficulty: "intermediate",
    servings: 4,
    prepTime: 25,
    cookTime: 60,
    tags: ["contains-gluten", "dairy-free"],
    nutrition: {
      calories: 670,
      protein: 44,
      carbs: 36,
      fat: 38,
    },
    description: "Simple herb-roasted chicken with torn country bread, market greens, and pan-jus vinaigrette.",
    imageUrl: "https://images.unsplash.com/photo-1518492104633-130d0cc84637?auto=format&fit=crop&w=900&q=80",
    instructions: [
      "Season chicken generously with salt, pepper, lemon zest, and thyme, then roast until deeply golden.",
      "Toast torn country bread in olive oil until crisp while the chicken rests.",
      "Toss the bread with arugula, shaved fennel, and roasted shallots.",
      "Whisk pan drippings with sherry vinegar and olive oil, then pour over the warm bread salad and serve with sliced chicken.",
    ],
    ingredients: [
      { name: "whole chicken", quantity: 4, unit: "lb" },
      { name: "country sourdough bread", quantity: 8, unit: "slice" },
      { name: "arugula", quantity: 4, unit: "cup" },
      { name: "fennel bulb", quantity: 1, unit: "each" },
      { name: "shallots", quantity: 3, unit: "each" },
      { name: "fresh thyme", quantity: 1, unit: "tbsp" },
      { name: "lemon zest", quantity: 1, unit: "tbsp" },
      { name: "sherry vinegar", quantity: 1.5, unit: "tbsp" },
      { name: "extra virgin olive oil", quantity: 4, unit: "tbsp" },
      { name: "black pepper", quantity: 1, unit: "tsp" },
    ],
  },
  {
    title: "Buttery Scrambled Eggs and Toast",
    cuisine: "american",
    mealType: "breakfast",
    protein: "egg",
    difficulty: "beginner",
    servings: 2,
    prepTime: 5,
    cookTime: 8,
    tags: ["vegetarian", "contains-dairy", "contains-egg", "contains-gluten"],
    nutrition: {
      calories: 360,
      protein: 18,
      carbs: 24,
      fat: 20,
    },
    description: "Soft scrambled eggs with butter served with crisp toast.",
    imageUrl: "https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=900&q=80",
    instructions: [
      "Whisk eggs with milk, salt, and pepper.",
      "Melt butter in a nonstick skillet and cook eggs over low heat, stirring gently until softly set.",
      "Toast bread slices until golden.",
      "Serve eggs immediately with toast.",
    ],
    ingredients: [
      { name: "large eggs", quantity: 4, unit: "each" },
      { name: "whole milk", quantity: 3, unit: "tbsp" },
      { name: "unsalted butter", quantity: 1, unit: "tbsp" },
      { name: "sandwich bread", quantity: 4, unit: "slice" },
      { name: "kosher salt", quantity: 0.5, unit: "tsp" },
      { name: "black pepper", quantity: 0.25, unit: "tsp" },
    ],
  },
  {
    title: "Everyday Banana Oatmeal",
    cuisine: "american",
    mealType: "breakfast",
    protein: "other",
    difficulty: "beginner",
    servings: 2,
    prepTime: 3,
    cookTime: 8,
    tags: ["vegetarian", "dairy-free", "contains-nuts"],
    nutrition: {
      calories: 320,
      protein: 10,
      carbs: 44,
      fat: 12,
    },
    description: "Quick stovetop oats topped with banana and peanut butter.",
    imageUrl: "https://images.unsplash.com/photo-1517673132405-a56a62b18caf?auto=format&fit=crop&w=900&q=80",
    instructions: [
      "Bring water and a pinch of salt to a simmer.",
      "Stir in oats and cook until creamy.",
      "Divide into bowls and top with sliced banana and peanut butter.",
      "Finish with cinnamon and a drizzle of honey.",
    ],
    ingredients: [
      { name: "rolled oats", quantity: 1, unit: "cup" },
      { name: "water", quantity: 2, unit: "cup" },
      { name: "banana", quantity: 1, unit: "each" },
      { name: "peanut butter", quantity: 2, unit: "tbsp" },
      { name: "honey", quantity: 1, unit: "tbsp" },
      { name: "ground cinnamon", quantity: 0.5, unit: "tsp" },
    ],
  },
  {
    title: "Simple Pancakes",
    cuisine: "american",
    mealType: "breakfast",
    protein: "egg",
    difficulty: "beginner",
    servings: 4,
    prepTime: 10,
    cookTime: 12,
    tags: ["vegetarian", "contains-dairy", "contains-egg", "contains-gluten"],
    nutrition: {
      calories: 420,
      protein: 12,
      carbs: 56,
      fat: 16,
    },
    description: "Fluffy pantry pancakes made with flour, milk, eggs, and butter.",
    imageUrl: "https://images.unsplash.com/photo-1528207776546-365bb710ee93?auto=format&fit=crop&w=900&q=80",
    instructions: [
      "Whisk flour, baking powder, sugar, and salt in a bowl.",
      "Whisk milk, eggs, and melted butter in a second bowl, then combine with dry ingredients.",
      "Cook batter on a buttered skillet over medium heat until bubbles form, then flip and finish.",
      "Serve warm with butter and syrup.",
    ],
    ingredients: [
      { name: "all-purpose flour", quantity: 2, unit: "cup" },
      { name: "baking powder", quantity: 2, unit: "tsp" },
      { name: "granulated sugar", quantity: 2, unit: "tbsp" },
      { name: "kosher salt", quantity: 0.5, unit: "tsp" },
      { name: "whole milk", quantity: 1.5, unit: "cup" },
      { name: "large eggs", quantity: 2, unit: "each" },
      { name: "unsalted butter", quantity: 3, unit: "tbsp" },
      { name: "maple syrup", quantity: 0.25, unit: "cup" },
    ],
  },
  {
    title: "Classic Grilled Cheese and Tomato Soup",
    cuisine: "american",
    mealType: "lunch",
    protein: "other",
    difficulty: "beginner",
    servings: 2,
    prepTime: 8,
    cookTime: 15,
    tags: ["vegetarian", "contains-dairy", "contains-gluten"],
    nutrition: {
      calories: 560,
      protein: 20,
      carbs: 46,
      fat: 32,
    },
    description: "Crisp buttered grilled cheese sandwiches with warm tomato soup.",
    imageUrl: "https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=900&q=80",
    instructions: [
      "Heat tomato soup in a saucepan with milk until hot.",
      "Butter bread and fill with cheddar slices.",
      "Cook sandwiches in a skillet until bread is golden and cheese is melted.",
      "Serve sandwiches with tomato soup.",
    ],
    ingredients: [
      { name: "sandwich bread", quantity: 4, unit: "slice" },
      { name: "cheddar cheese", quantity: 6, unit: "oz" },
      { name: "unsalted butter", quantity: 2, unit: "tbsp" },
      { name: "canned tomato soup", quantity: 2, unit: "cup" },
      { name: "whole milk", quantity: 0.5, unit: "cup" },
      { name: "black pepper", quantity: 0.25, unit: "tsp" },
    ],
  },
  {
    title: "Weeknight Spaghetti Marinara",
    cuisine: "italian",
    mealType: "dinner",
    protein: "other",
    difficulty: "beginner",
    servings: 4,
    prepTime: 10,
    cookTime: 20,
    tags: ["vegetarian", "contains-gluten", "contains-dairy"],
    nutrition: {
      calories: 500,
      protein: 16,
      carbs: 72,
      fat: 16,
    },
    description: "Simple spaghetti in garlic tomato sauce finished with Parmesan.",
    imageUrl: "https://images.unsplash.com/photo-1621996346565-e3dbc353d2e5?auto=format&fit=crop&w=900&q=80",
    instructions: [
      "Cook spaghetti in salted water until al dente.",
      "Saute onion and garlic in olive oil, then add crushed tomatoes and simmer.",
      "Season sauce with salt, pepper, and dried basil.",
      "Toss pasta with sauce and top with Parmesan.",
    ],
    ingredients: [
      { name: "spaghetti", quantity: 12, unit: "oz" },
      { name: "crushed tomatoes", quantity: 3, unit: "cup" },
      { name: "yellow onion", quantity: 1, unit: "each" },
      { name: "garlic cloves", quantity: 4, unit: "clove" },
      { name: "olive oil", quantity: 2, unit: "tbsp" },
      { name: "dried basil", quantity: 1, unit: "tsp" },
      { name: "Parmesan cheese", quantity: 0.5, unit: "cup" },
      { name: "kosher salt", quantity: 1, unit: "tsp" },
    ],
  },
  {
    title: "One-Pan Chicken Rice and Broccoli",
    cuisine: "american",
    mealType: "dinner",
    protein: "chicken",
    difficulty: "beginner",
    servings: 4,
    prepTime: 12,
    cookTime: 30,
    tags: ["dairy-free", "gluten-free"],
    nutrition: {
      calories: 520,
      protein: 36,
      carbs: 46,
      fat: 18,
    },
    description: "Basic chicken breast, rice, and broccoli cooked in one pan.",
    imageUrl: "https://images.unsplash.com/photo-1512058564366-c9e3c5b8051b?auto=format&fit=crop&w=900&q=80",
    instructions: [
      "Season chicken and sear in oil until browned, then remove.",
      "Saute onion and garlic, then stir in rice and broth.",
      "Return chicken to the pan, cover, and simmer until rice is tender.",
      "Steam broccoli in the same pan for the last few minutes and serve with lemon.",
    ],
    ingredients: [
      { name: "boneless skinless chicken breast", quantity: 1.5, unit: "lb" },
      { name: "long grain rice", quantity: 1.5, unit: "cup" },
      { name: "chicken broth", quantity: 3, unit: "cup" },
      { name: "broccoli florets", quantity: 3, unit: "cup" },
      { name: "yellow onion", quantity: 1, unit: "each" },
      { name: "garlic cloves", quantity: 3, unit: "clove" },
      { name: "olive oil", quantity: 2, unit: "tbsp" },
      { name: "lemon", quantity: 1, unit: "each" },
    ],
  },
  {
    title: "Ground Beef and Potato Skillet",
    cuisine: "american",
    mealType: "dinner",
    protein: "beef",
    difficulty: "beginner",
    servings: 4,
    prepTime: 12,
    cookTime: 25,
    tags: ["dairy-free", "gluten-free"],
    nutrition: {
      calories: 540,
      protein: 30,
      carbs: 34,
      fat: 30,
    },
    description: "Ground beef, potatoes, onion, and peas in a fast skillet dinner.",
    imageUrl: "https://images.unsplash.com/photo-1604908177522-402f7f0b61be?auto=format&fit=crop&w=900&q=80",
    instructions: [
      "Brown ground beef in a large skillet and drain excess fat if needed.",
      "Add diced potatoes and onion, then cook until potatoes are tender.",
      "Stir in garlic, tomato paste, paprika, and peas.",
      "Season with salt and pepper and cook until everything is hot.",
    ],
    ingredients: [
      { name: "ground beef", quantity: 1, unit: "lb" },
      { name: "russet potatoes", quantity: 2, unit: "each" },
      { name: "yellow onion", quantity: 1, unit: "each" },
      { name: "garlic cloves", quantity: 3, unit: "clove" },
      { name: "frozen peas", quantity: 1, unit: "cup" },
      { name: "tomato paste", quantity: 2, unit: "tbsp" },
      { name: "paprika", quantity: 1, unit: "tsp" },
      { name: "olive oil", quantity: 1, unit: "tbsp" },
    ],
  },
  {
    title: "Black Bean and Cheese Quesadillas",
    cuisine: "mexican",
    mealType: "lunch",
    protein: "legume",
    difficulty: "beginner",
    servings: 4,
    prepTime: 8,
    cookTime: 12,
    tags: ["vegetarian", "contains-dairy", "contains-gluten"],
    nutrition: {
      calories: 430,
      protein: 19,
      carbs: 44,
      fat: 20,
    },
    description: "Quick quesadillas with black beans, cheese, and onion.",
    imageUrl: "https://images.unsplash.com/photo-1618040996337-56904b7850b9?auto=format&fit=crop&w=900&q=80",
    instructions: [
      "Mash black beans lightly with cumin and salt.",
      "Spread beans and shredded cheese over tortillas, then fold.",
      "Cook on a skillet until crisp outside and melted inside.",
      "Slice and serve with salsa.",
    ],
    ingredients: [
      { name: "flour tortillas", quantity: 8, unit: "each" },
      { name: "canned black beans", quantity: 2, unit: "cup" },
      { name: "shredded cheddar cheese", quantity: 1.5, unit: "cup" },
      { name: "yellow onion", quantity: 0.5, unit: "each" },
      { name: "ground cumin", quantity: 1, unit: "tsp" },
      { name: "olive oil", quantity: 1, unit: "tbsp" },
      { name: "jarred salsa", quantity: 1, unit: "cup" },
    ],
  },
  {
    title: "Classic Tuna Salad Sandwiches",
    cuisine: "american",
    mealType: "lunch",
    protein: "fish",
    difficulty: "beginner",
    servings: 3,
    prepTime: 10,
    cookTime: 0,
    tags: ["dairy-free", "contains-gluten", "contains-egg"],
    nutrition: {
      calories: 390,
      protein: 28,
      carbs: 28,
      fat: 18,
    },
    description: "Pantry tuna salad on toasted bread with celery and lemon.",
    imageUrl: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=900&q=80",
    instructions: [
      "Drain tuna and mix with mayonnaise, diced celery, onion, lemon juice, salt, and pepper.",
      "Toast bread slices.",
      "Pile tuna salad onto bread and top with lettuce if desired.",
      "Serve immediately.",
    ],
    ingredients: [
      { name: "canned tuna", quantity: 15, unit: "oz" },
      { name: "mayonnaise", quantity: 0.33, unit: "cup" },
      { name: "celery stalk", quantity: 2, unit: "stalk" },
      { name: "red onion", quantity: 0.25, unit: "each" },
      { name: "lemon juice", quantity: 1, unit: "tbsp" },
      { name: "sandwich bread", quantity: 6, unit: "slice" },
      { name: "black pepper", quantity: 0.25, unit: "tsp" },
    ],
  },
  {
    title: "Creamy Stovetop Mac and Cheese",
    cuisine: "american",
    mealType: "dinner",
    protein: "other",
    difficulty: "beginner",
    servings: 4,
    prepTime: 8,
    cookTime: 15,
    tags: ["vegetarian", "contains-dairy", "contains-gluten"],
    nutrition: {
      calories: 610,
      protein: 24,
      carbs: 54,
      fat: 34,
    },
    description: "Classic macaroni and cheese with a quick cheddar sauce.",
    imageUrl: "https://images.unsplash.com/photo-1543332164-6e82f355bad5?auto=format&fit=crop&w=900&q=80",
    instructions: [
      "Boil macaroni until al dente and drain.",
      "Make a roux with butter and flour, then whisk in milk until smooth.",
      "Stir in cheddar until melted and season with salt and pepper.",
      "Fold in macaroni and serve hot.",
    ],
    ingredients: [
      { name: "elbow macaroni", quantity: 12, unit: "oz" },
      { name: "unsalted butter", quantity: 3, unit: "tbsp" },
      { name: "all-purpose flour", quantity: 3, unit: "tbsp" },
      { name: "whole milk", quantity: 2.5, unit: "cup" },
      { name: "cheddar cheese", quantity: 3, unit: "cup" },
      { name: "kosher salt", quantity: 1, unit: "tsp" },
      { name: "black pepper", quantity: 0.5, unit: "tsp" },
    ],
  },
]
