import type { GeneralPageEntry } from "../../../types/tutorial"

export const mealPlannerTutorial: GeneralPageEntry = {
  page: "/meal-planner",
  title: "Weekly Planner",
  description: "Move from week-level planning into one real scheduling action, then back out to confirm the result.",
  steps: [
    {
      id: 1,
      instruction: "Smart Plan is the quickest way to draft a week before you make manual adjustments.",
      highlightSelector: "[data-tutorial='planner-smart']",
      blockClick: true,
      lockInteraction: true,
    },
    {
      id: 2,
      instruction: "This full-week view helps you spot balance, repetition, and where ingredient overlap can save work later.",
      highlightSelector: "[data-tutorial='planner-overview']",
      blockClick: true,
      lockInteraction: true,
    },
    {
      id: 3,
      instruction: "Today's column is highlighted here so you always know exactly which day you are editing.",
      highlightSelector: "[data-tutorial='planner-today']",
      blockClick: true,
      lockInteraction: true,
    },
    {
      id: 4,
      instruction: "Open today's dinner slot so you can schedule the recipe you just saved.",
      highlightSelector: "[data-tutorial='planner-today-slot']",
      mandatory: true,
      lockInteraction: true,
      desktopOnly: true,
    },
    {
      id: 5,
      instruction: "Open today's dinner slot so you can schedule the recipe you just saved.",
      highlightSelector: "[data-tutorial='planner-today-slot']",
      mandatory: true,
      lockInteraction: true,
      mobileOnly: true,
    },
    {
      id: 6,
      instruction: "The recipe panel is where search, saved recipes, and slot assignment all come together.",
      highlightSelector: "[data-tutorial='planner-sidebar']",
      blockClick: true,
      lockInteraction: true,
    },
    {
      id: 7,
      instruction: "Switch to Saved so the recipe you put in a folder is ready to drop into the plan.",
      highlightSelector: "[data-tutorial='planner-favorites-tab']",
      mandatory: true,
      lockInteraction: true,
    },
    {
      id: 8,
      instruction: "Choose the saved recipe to add it to today's dinner slot.",
      highlightSelector: "[data-tutorial='planner-sidebar-recipe']",
      completionSelector: "[data-tutorial='planner-today-filled-slot']",
      mandatory: true,
      lockInteraction: true,
      desktopOnly: true,
    },
    {
      id: 9,
      instruction: "Choose the saved recipe for today's dinner slot.",
      highlightSelector: "[data-tutorial='planner-sidebar-recipe']",
      completionSelector: "[data-tutorial='planner-mobile-confirm-selections']",
      mandatory: true,
      lockInteraction: true,
      mobileOnly: true,
    },
    {
      id: 10,
      instruction: "Confirm the selected recipe so it is actually placed on today's dinner slot.",
      highlightSelector: "[data-tutorial='planner-mobile-confirm-selections']",
      completionSelector: "[data-tutorial='planner-today-filled-slot']",
      mandatory: true,
      lockInteraction: true,
      mobileOnly: true,
    },
    {
      id: 11,
      instruction: "Your filled day card updates right away, so you can verify the meal landed where you expected.",
      highlightSelector: "[data-tutorial='planner-today']",
      blockClick: true,
      lockInteraction: true,
    },
    {
      id: 12,
      instruction: "Close the panel to return to the full planner once the meal is scheduled.",
      highlightSelector: "[data-tutorial='planner-sidebar-close']",
      mandatory: true,
      lockInteraction: true,
      desktopOnly: true,
    },
  ],
}
